version: "3.9"
services:
  alpha:
    build: .
    image: conti-test
    container_name: alpha
    hostname: alpha
    tty: true
    stdin_open: true
    networks:
        conti-test:
          ipv4_address: 172.16.100.140
  bravo:
    image: conti-test
    container_name: bravo
    hostname: bravo
    tty: true
    stdin_open: true
    networks:
        conti-test:
          ipv4_address: 172.16.100.141
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 4g
    depends_on:
        - alpha
  charlie:
    image: conti-test
    container_name: charlie
    hostname: charlie
    tty: true
    stdin_open: true
    environment:
      - CONTI_ENV=${CONTI_ENV:-prod}
      - CONTI_DB_NAME=${CONTI_DB_NAME?You must specify CONTI_DB_NAME in the environment}
    ulimits:
        nofile:
          soft: 1048576
          hard: 1048576
    oom_kill_disable: true
    volumes:
        - ./data:/opt/data
    networks:
        conti-test:
          ipv4_address: 172.16.100.142
    depends_on:
        - alpha
        - bravo
networks:
  conti-test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.100.128/26
          gateway: 172.16.100.129