version: "3.9"
services:
  conti-test:
    build: .
  alpha:
    image: "conti-test"
    hostname: alpha
    networks:
        conti-test:
          ipv4_address: 172.16.100.140
    ports:
        - "22:22"
  bravo:
    image: "conti-test"
    hostname: bravo
    networks:
        conti-test:
          ipv4_address: 172.16.100.141
    cpu_percent: 10
    mem_limit: 4096
    ports:
        - "22:22"
    depends_on:
        - alpha
  charlie:
    image: "conti-test"
    hostname: charlie
    env_file: .env
    environment:
      - ${CONTI_ENV-default}
      - ${CONTI_DB_NAME?You must specify CONTI_DB_NAME in the environment}
    ulimits:
        nofile:
          soft: 1048576
    oom_kill_disable: true
    volumes:
        - ./data:/opt/data
    networks:
        conti-test:
          ipv4_address: 172.16.100.142
    ports:
        - "22:22"
    depends_on:
        - alpha
        - bravo
networks:
  conti-test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.100.128/26
          gateway: 172.16.100.129
