
- hosts: alpha
  become: true
  tasks:
    - name: Add the Apt Mirror Repo
      apt_repository:
          repo: deb {{ hostvars[item].apt_mirror }}
          state: present
      retries: 3
      delay: 5
      loop: "{{ groups.all }}"
    - name: Set timezone
      timezone:
        name: "{{ hostvars[item].timezone }}"
      retries: 3
      delay: 5
      loop: "{{ groups.all }}"
      
- hosts: west
  become: true
  tasks:
    - name: Adding the Welcome message to WEST
      shell: sudo sh -c 'echo "Once upon a time in the west." > /etc/motd'

- hosts: east
  become: true
  tasks:
    - name: Adding the Welcome message to EAST
      shell: sudo sh -c 'echo "Eastern promises." > /etc/motd'
